#!/usr/bin/env python
# -*- coding: cp936 -*-

# generated by wxGlade 0.6.5 (standalone edition) on Wed Mar 27 12:15:51 2013

import wx
import time
import os
import sys

# begin wxGlade: extracode
# end wxGlade

class MyFrame(wx.Frame):
    
    ''' It has mainly two parts,
    one is moment , I want to record at this time, what I did.
    the other is event, I want to record
    from start time after last time to end time
    what I have done or will do '''
    
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)

        #get ready for timer
        self.last_time = 0
        self.timer = wx.Timer(self, wx.ID_ANY)
        self.Bind(wx.EVT_TIMER, self.TimeOver, self.timer)

        self.label_4 = wx.StaticText(self, -1, "Moment :")
        self.moment_text = wx.TextCtrl(self, -1, "")
        self.now_time = wx.Button(self, -1, "Now")
        self.label_3 = wx.StaticText(self, -1, "Event :")
        self.moment_event = wx.TextCtrl(self, -1, "")
        self.moment_record = wx.Button(self, -1, "Record")
        self.moment_clear = wx.Button(self, -1, "Clear")
        self.label_5 = wx.StaticText(self, -1, "Start Time :")
        self.start_time = wx.TextCtrl(self, -1, "")
        self.alarm_now = wx.Button(self, -1, "Now")
        self.label_6 = wx.StaticText(self, -1, "Last  Time :")
        self.last_time = wx.TextCtrl(self, -1, "")
        self.thirty_m = wx.Button(self, -1, "30")
        self.ff_m = wx.Button(self, -1, "45")
        self.sixty_m = wx.Button(self, -1, "60")
        self.label_7 = wx.StaticText(self, -1, "End   Time :")
        self.end_time = wx.TextCtrl(self, -1, "")
        self.gen_end_button = wx.Button(self, -1, "Generate")
        self.alarm_event = wx.TextCtrl(self, -1, "")
        self.event_button = wx.Button(self, -1, "Record")
        self.alarm_start = wx.Button(self, -1, "Start")
        self.alarm_clear = wx.Button(self, wx.ID_CLEAR, "")
        self.quit_button = wx.Button(self, wx.ID_EXIT, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnMomentNow, self.now_time)
        self.Bind(wx.EVT_BUTTON, self.OnMomentRecord, self.moment_record)
        self.Bind(wx.EVT_BUTTON, self.OnClearMoment, self.moment_clear)
        self.Bind(wx.EVT_BUTTON, self.OnAlarmNow, self.alarm_now)
        self.Bind(wx.EVT_BUTTON, self.OnGenThirty, self.thirty_m)
        self.Bind(wx.EVT_BUTTON, self.OnGenFourFive, self.ff_m)
        self.Bind(wx.EVT_BUTTON, self.OnGenSixty, self.sixty_m)
        self.Bind(wx.EVT_BUTTON, self.OnGenEnd, self.gen_end_button)
        self.Bind(wx.EVT_BUTTON, self.OnEventAlarm, self.event_button)
        self.Bind(wx.EVT_BUTTON, self.OnAlarmStart, self.alarm_start)
        self.Bind(wx.EVT_BUTTON, self.OnClearAlarm, self.alarm_clear)
        self.Bind(wx.EVT_BUTTON, self.OnClose, self.quit_button)
        # end wxGlade

        self.Bind(wx.EVT_CLOSE, self.CloseWindow)

    def CloseWindow(self, event):
        self.Destroy()

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Event Record")
        self.label_4.SetMinSize((55, 14))
        self.label_3.SetMinSize((55, 14))
        self.thirty_m.SetMinSize((25, 24))
        self.ff_m.SetMinSize((25, 24))
        self.sixty_m.SetMinSize((25, 24))
        self.event_button.SetMinSize((126,30))
        self.alarm_start.SetMinSize((106, 30))
        self.alarm_clear.SetMinSize((107, 30))
        self.quit_button.SetMinSize((75, 40))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(self.label_4, 0, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_13.Add(self.moment_text, 1, wx.LEFT | wx.TOP | wx.BOTTOM | wx.EXPAND, 3)
        sizer_13.Add(self.now_time, 0, wx.LEFT | wx.RIGHT | wx.TOP, 3)
        sizer_10.Add(sizer_13, 1, wx.TOP | wx.BOTTOM | wx.EXPAND, 3)
        sizer_12.Add(self.label_3, 0, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_12.Add(self.moment_event, 1, wx.LEFT | wx.RIGHT | wx.EXPAND, 3)
        sizer_10.Add(sizer_12, 1, wx.TOP | wx.BOTTOM | wx.EXPAND, 2)
        sizer_11.Add(self.moment_record, 1, wx.LEFT | wx.RIGHT | wx.EXPAND, 10)
        sizer_11.Add(self.moment_clear, 1, wx.LEFT | wx.RIGHT | wx.EXPAND, 10)
        sizer_10.Add(sizer_11, 1, wx.TOP | wx.BOTTOM | wx.EXPAND, 2)
        sizer_3.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_15.Add(self.label_5, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_15.Add(self.start_time, 1, wx.ALL | wx.EXPAND, 3)
        sizer_15.Add(self.alarm_now, 1, wx.ALL | wx.EXPAND, 3)
        sizer_14.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_16.Add(self.label_6, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_16.Add(self.last_time, 0, wx.ALL | wx.EXPAND, 3)
        sizer_18.Add(self.thirty_m, 0, 0, 0)
        sizer_18.Add(self.ff_m, 0, 0, 0)
        sizer_18.Add(self.sixty_m, 0, wx.EXPAND, 3)
        sizer_16.Add(sizer_18, 0, wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_14.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_17.Add(self.label_7, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_17.Add(self.end_time, 2, wx.ALL | wx.EXPAND, 3)
        sizer_17.Add(self.gen_end_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_14.Add(sizer_17, 1, wx.EXPAND, 0)
        sizer_6.Add(sizer_14, 1, wx.EXPAND, 0)
        label_1 = wx.StaticText(self, -1, "Event :", style=wx.ALIGN_CENTRE)
        label_1.SetMinSize((60, 25))
        label_1.SetBackgroundColour(wx.Colour(240, 240, 240))
        label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        sizer_7.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(self.alarm_event, 1, wx.LEFT | wx.RIGHT | wx.EXPAND, 6)
        sizer_6.Add(sizer_7, 1, wx.TOP | wx.BOTTOM | wx.EXPAND, 6)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5.Add(self.event_button, 1, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_5.Add(self.alarm_start, 1, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_5.Add(self.alarm_clear, 1, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_2.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.quit_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnMomentNow(self, event):  # wxGlade: MyFrame.<event_handler>
        '''click this, set the time showed in moment_text text_ctrl'''
        now_time = time.asctime()
        self.moment_text.SetValue(now_time)

    def get_time(self, text_ctrl):
        '''get float point number from text_ctrl's value'''

        # first get the value in string
        the_time = text_ctrl.GetValue()

        # if nothing is got
        if the_time == '': 
            the_time = time.time()              # then get the time right now in float
            text_ctrl.SetValue(time.asctime())  # set the string to text ctrl
            return the_time

        try :
            # convert string of time to float point of time
            string = time.strptime(the_time, "%a %b %d %H:%M:%S %Y")
            the_time = time.mktime(string)
            return the_time
            
        except ValueError:
            # if the string is not a right time format
            message = wx.MessageDialog(None, "Error Input Type", 'Warnning',
                                    wx.YES_NO)
                
            if message.ShowModal():
                pass
            message.Destroy()
            return -1

    def open_day_file(self, parent_path, str_of_time):
        ''' From the string of time to get the path of file to append.'''
        # split the string to get day \ year and clock
        struct_time = str_of_time.split()

        # now care about day
        day = int(struct_time[2])

        # file name is like this  month_day_year
        name = str(struct_time[1] + '_' + struct_time[2] + '_' + struct_time[-1] + '.txt')

        # append to the file
        target_file = file(parent_path + name, 'a')
        return target_file, struct_time

    def get_event(self, event_text):
        '''get the event from the event_text'''
        event = event_text.GetValue()

        # if event is empty
        if event == '':
            error_flag = "No Event, What you do?"
            message = wx.MessageDialog(None, error_flag,
                                       'Warnning', wx.YES_NO)
            if message.ShowModal():
                pass
            message.Destroy()
            return None
        
        return event
        
    
    def OnMomentRecord(self, event):  # wxGlade: MyFrame.<event_handler>
        ''' Record the moment and the relate event to moment_record file.'''
        # get the event content
        event = self.get_event(self.moment_event)
        if event == None:
            return

        # get the moment time in string format, if can't get right now time
        moment = time.ctime(self.get_time(self.moment_text))

        # open the day file to write
        parent_path = "F:\\self\\moment_record\\"

        target_file, struct_time = self.open_day_file(parent_path, moment)

        # write in format : hour:minute:second --> event
        event = event.encode('utf-8')
        target_file.write(struct_time[-2] + " --> " + event + '\n')
        
        #never forget to close
        target_file.close()
        

    def OnClearMoment(self, event):  # wxGlade: MyFrame.<event_handler>
        '''clear the text ctrl in moment part, include moment_text and moment_event'''
        self.moment_text.SetValue('')
        self.moment_event.SetValue('')

    def OnAlarmNow(self, event):  # wxGlade: MyFrame.<event_handler>
        '''click this, set the time showed in start_time text_ctrl, just in event part'''
        now_time = time.asctime()
        self.start_time.SetValue(now_time)

    def TimeOver(self, event):
        ''' when the timer call timeover, get an alarm of timeover to me.
        and record what I have done'''

        # record the event, start, end, last
        self.OnEventAlarm(event)

        # Set button label to start and clear text in all of part event
        self.alarm_start.SetLabel("Start")

        # call a music file to inform me
        path = os.getcwd()
        
        if path.find('ython') < 0:
            filename = '海阔天空.mp3'
        else :
            filename = r'F:\mycode\Tools\hai_kuo_tian_kong.mp3'
        
        os.startfile(filename)

        # clear
        self.OnClearAlarm(event)
        self.timer.Stop()
        self.timer.Destroy()

    def OnEventAlarm(self, event):  # wxGlade: MyFrame.<event_handler>
        ''' record the event, time(start, end, last) in event record file'''

        if self.timer.IsRunning():
        # timer is running , stop it, reset the label
            self.timer.Stop()
            self.alarm_start.SetLabel("Start")

        # last may get from the last_time text_ctrl, but I just do this to compute
        last = self.OnGenEnd(event)

        # get the content of event
        event = self.get_event(self.alarm_event)
        if event == None or last < 0:
            return

        # get the string of start and end time,
        start_str = self.start_time.GetValue()
        end_str = self.end_time.GetValue()

        # open the day file to write
        parent_path = "F:\\self\\event_record\\"
        target_file, struct_time = self.open_day_file(parent_path, start_str)
        
        # in the format like this : start to end  last  --> event
        event = event.encode('utf-8')
        target_file.write(start_str.split()[-2] + " to " + end_str.split()[-2] + \
                          '  %5.2f  '%last + ' --> ' + event + '\n')
        target_file.close()

        
    def OnAlarmStart(self, event):  # wxGlade: MyFrame.<event_handler>
        ''' click on this button and set the status of the timer:
        if timer is running, click the button, timer is stopped.
        else start timer for last minutes.'''
        
        if self.timer.IsRunning():
            # timer is running , stop it, reset the label
            self.timer.Stop()
            self.alarm_start.SetLabel("Start")
            self.OnClearAlarm()
            
        else :
            # timer is not running , run it, for last time minutes
            last_time = self.OnGenEnd(event)
            
            if last_time > 0:
                self.timer.Start(last_time * 60000)
                self.alarm_start.SetLabel("Stop")
                
    def OnClearAlarm(self, event):  # wxGlade: MyFrame.<event_handler>
        ''' clear all in event part'''
        self.last_time.SetValue('')
        self.start_time.SetValue('')
        self.end_time.SetValue('')
        # I think the event may be useful after clean 
        #self.alarm_event.SetValue('')

    def OnGenThirty(self, event):  # wxGlade: MyFrame.<event_handler>
        self.last_time.SetValue('30')

    def OnGenFourFive(self, event):  # wxGlade: MyFrame.<event_handler>
        self.last_time.SetValue('45')

    def OnGenSixty(self, event):  # wxGlade: MyFrame.<event_handler>
        self.last_time.SetValue('60')

    def OnGenEnd(self, event):  # wxGlade: MyFrame.<event_handler>

        try :
            # get last time in string
            last_time = self.last_time.GetValue()

            # get start time in float point number
            start_time = self.get_time(self.start_time)

            # if start time is right but without last time,
            # assumpt that I have entred end time
            # or the event end now,
            # the end time should be right now
            if start_time > 0 and last_time == '':            
            
                end_time = self.get_time(self.end_time)
                
                if end_time < 0:
                # maybe I entred end time, but in wrong format
                # so get the time of right now!
                    end_time = time.time()
                    self.end_time.SetValue(time.asctime())
                    
                elif end_time < start_time:
                # if the end time is before the start time,
                # there is no use to gene the end time
                    return -1
                
                # just know start time and end time, so compute the last time    
                last_time = (end_time  - start_time) / 60

                self.last_time.SetValue('%.2f'%last_time)                
                return last_time

            # last is not empty
            last_time = float(last_time)           

            # compute the end time
            if start_time > 0 and last_time > 0 :
                end_time = start_time + float(last_time) * 60
                self.end_time.SetValue(time.ctime(end_time))
            
            return last_time
        
        except ValueError:
            
            message = wx.MessageDialog(None, "None of Last time or start time",
                                       'Warnning', wx.YES_NO)
                
            if message.ShowModal():
                    pass
            message.Destroy()

            return -1
        
    def OnClose(self, event):  # wxGlade: MyFrame.<event_handler>
        self.CloseWindow(event)

# end of class MyFrame
if __name__ == "__main__":
    moment_event_alarm = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    main_frame = MyFrame(None, -1, "")
    moment_event_alarm.SetTopWindow(main_frame)
    main_frame.Show()
    moment_event_alarm.MainLoop()
